### ISSUE TITLE
期望支持选择表情并屏蔽

### ISSUE THREAD

**Issue by QingFeng-awa** [elegantland/qqMessageBlocker#1]
目前直接复制QQ表情只会复制到`[表情]`,不能粘贴到设置里实现屏蔽。
所以我希望可以在设置里实现选择表情来实行屏蔽操作。
> 有的人总喜欢发单个表情,看起来像是阴阳人,但是你要说TA,TA又有各种理由来解释,真的很无语。

**Comment by elegantland** [comment]
好主意，不过我发现qqnt版有表情和超级表情之分，我将在明天对这两种表情和图片类进行写屏蔽规则，版本号为1.0.2，现在已经在本地初步完成该功能。
不过针对你  目前直接复制QQ表情只能复制到[表情]， 这个问题来说的话，你还需要提前下一个devtools来获取每一个表情的具体id，我明天将会在版本1.0.2更新的时候重写一下readme，到时候会提供屏蔽教程。

**Comment by elegantland** [comment]
已完成该功能，希望这能帮助你
