### ISSUE TITLE
未适配深色模式

### ISSUE THREAD

**Issue by QingFeng-awa** [elegantland/qqMessageBlocker#3]
详情看图
![image](https://github.com/user-attachments/assets/feb94ff7-9933-4344-889a-0754bfa4d165)

**Comment by elegantland** [comment]
确实应该适配一下...

**Comment by elegantland** [comment]
不过依然要提醒你一下这个页面几乎失效，只有查看功能

**Comment by elegantland** [comment]
我重新写了一下设置界面，当前版本2.0.0已经适配了夜间模式和可以在设置界面添加相关屏蔽词，欢迎使用和反馈
