### ISSUE TITLE
设置界面显示问题

### ISSUE THREAD

**Issue by QingFeng-awa** [elegantland/qqMessageBlocker#5]
https://github.com/user-attachments/assets/ff4b069e-7429-4de3-a265-b57e3f215ff4

这个问题目前只有MB这一个插件有,所以我先在这发issue,如果你解决不了再发LL本体看看。
> 之后把其他插件关了又试了一遍,问题还在,排除其他插件奇奇怪怪的问题。

**Comment by elegantland** [comment]
这依然是我的模块的问题，让我修复一下

**Comment by elegantland** [comment]
我已经排查过了，就是我的设置界面没写好的问题，不过最近没时间得过两天才能修复了:(

**Comment by elegantland** [comment]
比我想象的顺利，你用一下我的最新的renderer.js看一下是否正常?现在是2.0.3，我将一会更新release

**Comment by Hiraeth-Wave** [comment]
这个issue解决了,但是你的`manifest.json`版本号还是2.0.1,记得改下重传release。
