### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by kuyunjian** [elegantland/qqMessageBlocker#7]
有没有可能开发导出聊天记录的功能

**Comment by elegantland** [comment]
事实上2.0.6版本有过类似的尝试，但是目前遇到了不少麻烦，所以导出聊天记录的功能不会加入目前这个插件而是做一个新的插件，新的插件主要是防撤回信息和导入导出聊天记录（但好像已经有现成的插件和其他方案了，所以一直在犹豫是否上传到github）

**Comment by kuyunjian** [comment]
> 事实上2.0.6版本有过类似的尝试，但是目前遇到了不少麻烦，所以导出聊天记录的功能不会加入目前这个插件而是做一个新的插件，新的插件主要是防撤回信息和导入导出聊天记录（但好像已经有现成的插件和其他方案了，所以一直在犹豫是否上传到github）
哦哦这样，防撤回我记得是有的，导出聊天记录这个功能没去仔细看。
最新版本qqnt里电脑端没仔细看，目前在一个手机端导出聊天记录的github项目里说qqnt架构导出比较麻烦，一直没有进展

**Comment by kuyunjian** [comment]
> 事实上2.0.6版本有过类似的尝试，但是目前遇到了不少麻烦，所以导出聊天记录的功能不会加入目前这个插件而是做一个新的插件，新的插件主要是防撤回信息和导入导出聊天记录（但好像已经有现成的插件和其他方案了，所以一直在犹豫是否上传到github）


哦哦这样，防撤回我记得是有的，导出聊天记录这个功能没去仔细看。
最新版本qqnt里电脑端没仔细看，目前在一个手机端导出聊天记录的github项目里说qqnt架构导出比较麻烦，一直没有进展

**Comment by elegantland** [comment]
https://github.com/elegantland/qqMessageSave
