### ISSUE TITLE
添加新功能

### ISSUE THREAD

**Issue by luoyu-lty** [elegantland/qqMessageBlocker#8]
添加 屏蔽消息记录 功能，将含有屏蔽词的消息记录也屏蔽

**Comment by elegantland** [comment]
没太懂，聊天记录的消息是有被屏蔽的，转发的聊天记录也有被屏蔽，不知道你说的是什么功能，请给出具体需要被屏蔽的东西

**Comment by luoyu-lty** [comment]
聊天记录点开之前会有几条消息显示在外面的，能不能把那个给屏蔽了，在我设备上能看到添加屏蔽词的消息的，点进去就没有。
还有就是聊天窗口左边的消息列表能否也屏蔽

**Comment by elegantland** [comment]
聊天窗口左边的消息列表能屏蔽，下个版本改

【聊天记录点开之前会有几条消息显示在外面的，能不能把那个给屏蔽了，在我设备上能看到添加屏蔽词的消息的，点进去就没有。】你这个说的也是左边的消息列表吧？

**Comment by luoyu-lty** [comment]
> 聊天记录点开之前会有几条消息显示在外面的，能不能把那个给屏蔽了，在我设备上能看到添加屏蔽词的消息的，点进去就没有。

这个指的是合并转发的消息记录

**Comment by elegantland** [comment]
那个有点麻烦，最近封号多更新有点慢，你过段时间再看看吧

**Comment by luoyu-lty** [comment]
可以，先把好写的写了，之后慢慢搞🫠🫠

**Comment by elegantland** [comment]
> 这个指的是合并转发的消息记录

这个问题已被解决，左边消息列表由于有点特殊目前存在无法解决的bug，2.0.8以及后续版本将不处理这部分问题，后续也不会对左边的消息列表进行任何修改，是否还有其他疑问？

**Comment by luoyu-lty** [comment]
没有了，感谢😌
